package resolverService

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"app-gateway/graph/model"
	"context"
	"fmt"
)

// CreateApp is the resolver for the createApp field.
func (r *mutationResolver) CreateApp(ctx context.Context, input model.AppInput) (*model.App, error) {
	panic(fmt.Errorf("not implemented: CreateApp - createApp"))
}

// Apps is the resolver for the apps field.
func (r *queryResolver) Apps(ctx context.Context) ([]*model.App, error) {
	panic(fmt.Errorf("not implemented: Apps - apps"))
}

// App is the resolver for the app field.
func (r *queryResolver) App(ctx context.Context, id string) (*model.App, error) {
	panic(fmt.Errorf("not implemented: App - app"))
}
