# .github/issue_templates/epic.yml
name: Epic
description: Use this template to create a high-level Epic story for cloud infrastructure software.
labels: ["Type: Epic"]
body:
  - type: markdown
    attributes:
      value: "Provide a high-level summary of the Epic story related to our cloud infrastructure."
  - type: textarea
    id: components-involved
    attributes:
      label: "Components / Services Affected"
      description: "Which core components or services of our cloud infrastructure will be primarily involved or affected by this epic?"
      placeholder: "e.g., Compute Service, Storage Service, Networking Layer, Identity Management."
      value: "Mention the components or services that will be primarily involved or affected by this epic."
  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "Are there any other epics or significant pieces of work that need to be completed before or in parallel with this epic? (Link issue numbers if applicable)."
      placeholder: "e.g., Depends on #45 (Core Networking Upgrade)."
      value: "dependencies for this epic."