# .github/issue_templates/epic.yml
name: Epic
description: Use this template to create a high-level Epic story.
labels: ["Type: Epic"]
assignees: []
body:
  - type: markdown
    attributes:
      label: "Overview"
      value: "Provide a high-level summary of the Epic story."
  - type: textarea
    id: business-value
    attributes:
      label: "Business Value / Goal"
      description: "What business value will this epic deliver?"
      placeholder: "e.g., Increase user engagement by 20%."
      value: ""
      validations:
        required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "High-Level Acceptance Criteria"
      description: "What are the key outcomes or conditions that will signify completion of this epic?"
      placeholder: "- Feature A is implemented.\n- User feedback is positive."
      value: ""
      validations:
        required: true
  - type: textarea
    id: out-of-scope
    attributes:
      label: "Out of Scope"
      description: "What is explicitly *not* included in this epic?"
      placeholder: "e.g., Integration with external system X."
      value: ""