# .github/issue_templates/story.yml
name: Story
description: Use this template for a user story.
labels: ["Type: Story"]
body:
  - type: markdown
    attributes:
      value: "Provide a clear and concise description of the user story."