# .github/issue_templates/subtask.yml
name: Task
description: Use this template to create a specific task that contributes to an Epic.
labels: ["Type: Task"]
body:
  - type: markdown
    attributes:
      value: "Provide a clear and concise description of the task."
  - type: textarea
    id: high-level-acceptance-criteria
    attributes:
      label: "High-Level Acceptance Criteria"
      description: "What are the key outcomes or conditions that will signify completion of this epic from an infrastructure perspective?"
      placeholder: "- The new compute service can handle X number of requests per second.\n- Storage latency is below Y milliseconds."
      value: "high-level acceptance criteria for the epic."


