# .github/issue_templates/subtask.yml
name: Task
description: Use this template to create a specific task that contributes to an Epic.
labels: ["Type: Task"]
body:
  - type: markdown
    attributes:
      value: "Provide a clear and concise description of the task."