[package]
name = "brahma-schema-master"
version = "0.1.0"
edition = "2021"


[dependencies]
async-std = "1.13.0"
clap = { version = "4.5.26", features = ["derive"] }
dotenv = "0.15.0"
postgres = "0.19.9"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] } 